name: Docker Compose CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and run Docker Compose
      run: |
        docker-compose up --build -d
        docker-compose ps

    - name: Run tests
      run: |
        docker-compose exec app pytest

    - name: Stop Docker Compose
      run: docker-compose down
